import json, os, random
chapters = {
1:("Introduction to Flying",[
("flight history","Wright brothers","Who made the first sustained, controlled, powered heavier-than-air flight in 1903?","Wilbur and Orville Wright",["Sir George Cayley","Joseph and Etienne Montgolfier","Glenn Curtiss"]),
("flight history","Cayley","Who is identified as the Father of Aerial Navigation?","Sir George Cayley",["Otto Lilienthal","Leonardo da Vinci","P. E. Fansler"]),
("FAA and regulation","FAA role","Which organization regulates U.S. civil aviation safety and operates the national air traffic system?","Federal Aviation Administration",["National Transportation Safety Board","National Weather Service","Transportation Security Administration"]),
("FAA and regulation","CFR","Where are binding federal civil aviation regulations codified?","Title 14 of the Code of Federal Regulations",["Aeronautical Information Manual","Advisory Circulars","Pilot's Handbook of Aeronautical Knowledge"]),
("aeronautical publications","AIM","Which publication provides basic flight information and ATC procedures for use in the National Airspace System?","Aeronautical Information Manual (AIM)",["Aircraft registration certificate","Airworthiness certificate","Pilot logbook"]),
("aeronautical publications","AC","What is the primary purpose of an FAA Advisory Circular?","Provide guidance and information on aviation subjects",["Create a pilot certificate","Replace federal regulations","Authorize flight in prohibited airspace"]),
("pilot certification","student pilot","What is the minimum age for a student pilot certificate for airplanes?","16 years",["14 years","17 years","18 years"]),
("pilot certification","private pilot","Which certificate generally supports personal and recreational flying without acting as pilot for compensation or hire?","Private pilot certificate",["Commercial pilot certificate","Airline transport pilot certificate","Mechanic certificate"]),
("pilot certification","commercial pilot","Which certificate provides expanded privileges to act as pilot for compensation or hire, subject to applicable rules?","Commercial pilot certificate",["Student pilot certificate","Recreational pilot certificate","Ground instructor certificate"]),
("flight training","CFI","Who normally provides authorized flight instruction and training endorsements?","Certificated Flight Instructor (CFI)",["Designated Pilot Examiner","Airport manager","Air traffic controller"]),
("flight training","DPE","Who may administer an FAA practical test when appropriately designated?","Designated Pilot Examiner (DPE)",["Any private pilot","Airport manager","Aircraft owner"]),
("aircraft classification","category/class","Which pair is an example of airplane classes?","Single-engine land and multiengine land",["Airplane and rotorcraft","Private and commercial","VFR and IFR"]),]),
2:("Aeronautical Decision-Making",[
("ADM","definition","What is aeronautical decision-making (ADM)?","A systematic approach to choosing the best course of action in aviation",["A method of calculating aircraft weight","A radio navigation technique","A maintenance inspection program"]),
("risk management","hazard","What is a hazard?","A condition, event, or circumstance that could lead to an undesired outcome",["The numerical probability of an accident","A guaranteed accident","A completed corrective action"]),
("risk management","risk","What does risk describe?","The future impact of a hazard that is not controlled or eliminated",["Only the cost of a flight","The aircraft's empty weight","A pilot certificate limitation"]),
("hazardous attitudes","anti-authority","Which antidote counters the anti-authority hazardous attitude?","Follow the rules; they are usually right",["Do it quickly","It will not happen to me","I can do it"]),
("hazardous attitudes","impulsivity","Which antidote counters impulsivity?","Not so fast; think first",["What is the use?","I am not helpless","It could happen to me"]),
("hazardous attitudes","invulnerability","Which antidote counters invulnerability?","It could happen to me",["I can do it","Do it quickly","Rules do not apply"]),
("hazardous attitudes","macho","Which antidote counters the macho attitude?","Taking chances is foolish",["I can do it","Nothing will happen","Act immediately"]),
("hazardous attitudes","resignation","Which antidote counters resignation?","I am not helpless; I can make a difference",["What is the use?","Take chances","Ignore the rules"]),
("risk management","PAVE","What does PAVE help a pilot evaluate?","Pilot, Aircraft, enVironment, and External pressures",["Power, Altitude, Velocity, Engine","Plan, Airspeed, Visibility, Equipment","Pilot, Airport, VOR, Emergency"]),
("SRM","5P","Which set belongs to the 5P check?","Plan, Plane, Pilot, Passengers, Programming",["Pilot, Power, Pressure, Position, Performance","Plan, Propeller, Payload, Pressure, Position","Plane, Pavement, Pattern, Power, Procedure"]),
("decision process","3P","What are the three steps in the 3P model?","Perceive, Process, Perform",["Plan, Predict, Proceed","Prepare, Practice, Perform","Perceive, Prevent, Protect"]),
("decision process","DECIDE","In the DECIDE model, what is the first step?","Detect that a change has occurred",["Evaluate the outcome","Do the necessary action","Choose a desired outcome"]),]),
3:("Aircraft Construction",[
("classification","airplane","How does 14 CFR part 1 define an airplane?","An engine-driven fixed-wing aircraft supported in flight by the dynamic reaction of air against its wings",["Any aircraft lighter than air","A rotorcraft supported by rotating blades","Any unpowered glider"]),
("structures","fuselage","What is the primary role of the fuselage?","Provide the main body that accommodates occupants/cargo and joins major components",["Generate all aircraft thrust","Control roll directly","Measure static pressure"]),
("structures","monocoque","What carries most loads in a monocoque fuselage?","The stressed skin",["Only internal trusses","The landing gear tires","The control cables"]),
("structures","semimonocoque","What characterizes semimonocoque construction?","Stressed skin reinforced by internal structural members",["Fabric with no internal support","A single solid block","Only external struts"]),
("wings","spar","What is a wing spar?","A principal structural member running spanwise through the wing",["A movable yaw control","A fuel vent only","A cockpit instrument"]),
("wings","ribs","What do wing ribs primarily do?","Give the wing its airfoil shape and transfer loads",["Create ignition sparks","Control nosewheel steering","Measure altitude"]),
("empennage","horizontal stabilizer","Which empennage surface primarily provides longitudinal stability?","Horizontal stabilizer",["Vertical stabilizer","Aileron","Wing flap"]),
("empennage","vertical stabilizer","Which empennage surface primarily provides directional stability?","Vertical stabilizer",["Horizontal stabilizer","Elevator","Spoiler"]),
("landing gear","tricycle","What is a tricycle landing gear arrangement?","Two main wheels with a nosewheel",["Two main wheels with a tailwheel","One wheel under each wingtip only","Skids with no wheels"]),
("materials","aluminum","Why are aluminum alloys widely used in aircraft structures?","They combine useful strength with relatively low weight",["They are completely immune to corrosion","They are heavier than steel","They cannot be formed"]),
("materials","composites","What is a major advantage of composite aircraft materials?","High strength-to-weight characteristics and ability to form complex shapes",["They require no inspection","They cannot be damaged","They conduct electricity exactly like aluminum"]),
("loads","stress","Which structural stresses are commonly considered in aircraft?","Tension, compression, torsion, shear, and bending",["Lift, drag, thrust, and weight only","Voltage, current, resistance, and power","Pitch, roll, yaw, and trim"]),]),
4:("Principles of Flight",[
("atmosphere","composition","Approximately what percentage of the atmosphere is nitrogen?","78 percent",["21 percent","50 percent","1 percent"]),
("atmosphere","oxygen","Approximately what percentage of the atmosphere is oxygen?","21 percent",["78 percent","1 percent","50 percent"]),
("atmosphere","pressure","What generally happens to atmospheric pressure as altitude increases?","It decreases",["It increases","It remains constant","It becomes zero immediately"]),
("atmosphere","density","What generally happens to air density as altitude increases?","It decreases",["It increases","It remains constant","It doubles every 1,000 feet"]),
("fluid behavior","Bernoulli","What does Bernoulli's principle relate in a flowing fluid?","Higher velocity is associated with lower static pressure",["Higher velocity always means higher static pressure","Pressure is unrelated to velocity","Only temperature controls pressure"]),
("fluid behavior","Newton","Which Newtonian idea helps explain aerodynamic force?","A force results from changing the momentum/direction of airflow",["Air has no mass","Every object remains motionless in flight","Pressure cannot create force"]),
("airfoils","chord","What is an airfoil chord line?","A straight line from the leading edge to the trailing edge",["The curved upper surface only","A line perpendicular to relative wind","The wingtip path"]),
("airfoils","camber","What is camber?","The curvature of an airfoil surface",["The wing's span","The aircraft's weight","The propeller diameter"]),
("airfoils","AOA","What is angle of attack?","The angle between the chord line and relative wind",["The angle between the horizon and fuselage","The bank angle","The runway slope"]),
("airfoils","relative wind","Relative wind is opposite and parallel to what?","The flight path of the airfoil through the air",["The aircraft heading only","The runway centerline","The Earth's magnetic field"]),
("pressure","static/dynamic","Dynamic pressure depends primarily on what two air properties?","Air density and the square of velocity",["Only temperature and humidity","Only aircraft weight","Magnetic variation and deviation"]),
("center of pressure","movement","What can happen to an airfoil's center of pressure as angle of attack changes?","Its location can move along the chord",["It is permanently fixed at the wingtip","It always remains at the leading edge","It disappears above sea level"]),]),
5:("Aerodynamics of Flight",[
("four forces","lift","Which aerodynamic force acts perpendicular to the flight path?","Lift",["Drag","Thrust","Weight"]),
("four forces","drag","Which force generally acts rearward and parallel to the relative wind?","Drag",["Lift","Weight","Thrust"]),
("four forces","weight","Which force acts toward the center of Earth?","Weight",["Lift","Thrust","Drag"]),
("four forces","thrust","Which force is produced by the powerplant/propeller or rotor to oppose drag?","Thrust",["Weight","Lift","Induced drag"]),
("AOA and lift","critical AOA","What directly causes an aerodynamic stall?","Exceeding the wing's critical angle of attack",["A specific low airspeed only","Reducing bank angle","Flying below gross weight"]),
("drag","induced drag","When is induced drag generally greatest?","At low airspeed and high angle of attack",["At high airspeed and low angle of attack","Only while parked","It is constant at all speeds"]),
("drag","parasite drag","How does parasite drag generally change as airspeed increases?","It increases",["It decreases to zero","It remains constant","It reverses direction"]),
("turns","load factor","What happens to load factor in a level coordinated turn as bank angle increases?","It increases",["It decreases","It remains exactly 1 G","It becomes zero"]),
("stalls","accelerated stall","An accelerated stall can occur at what condition?","At a higher-than-normal stall speed when load factor is increased",["Only at zero bank","Only with the engine stopped","Only below sea level"]),
("stability","longitudinal","Longitudinal stability concerns motion about which axis?","Lateral axis (pitch)",["Longitudinal axis (roll)","Vertical axis (yaw)","No axis"]),
("stability","directional","Directional stability concerns motion about which axis?","Vertical axis (yaw)",["Lateral axis (pitch)","Longitudinal axis (roll)","No axis"]),
("wake turbulence","vortices","Where are wingtip vortices strongest?","Behind a heavy, clean, slow aircraft",["Behind a light, dirty, fast aircraft","Only after engine shutdown","Only above thunderstorms"]),]),
6:("Flight Controls",[
("primary controls","ailerons","Which primary control surfaces control roll?","Ailerons",["Elevator","Rudder","Flaps"]),
("primary controls","elevator","Which primary control surface controls pitch?","Elevator",["Ailerons","Rudder","Spoilers"]),
("primary controls","rudder","Which primary control surface controls yaw?","Rudder",["Ailerons","Elevator","Flaps"]),
("axes","longitudinal","Roll occurs about which axis?","Longitudinal axis",["Lateral axis","Vertical axis","Transverse runway axis"]),
("axes","lateral","Pitch occurs about which axis?","Lateral axis",["Longitudinal axis","Vertical axis","Magnetic axis"]),
("axes","vertical","Yaw occurs about which axis?","Vertical axis",["Lateral axis","Longitudinal axis","Chord axis"]),
("adverse yaw","cause","What causes adverse yaw during aileron deflection?","Unequal drag created by the differently deflected ailerons",["Equal lift on both wings","Elevator trim only","Static pressure error"]),
("secondary controls","flaps","What is a primary aerodynamic effect of extending flaps?","Increase lift and drag",["Decrease both lift and drag","Control yaw only","Eliminate induced drag"]),
("secondary controls","spoilers","What do spoilers generally do when deployed?","Reduce lift and increase drag",["Increase lift and reduce drag","Control engine mixture","Increase fuel pressure"]),
("trim","trim tab","What is the purpose of a trim system?","Relieve sustained control pressure",["Increase maximum gross weight","Replace the rudder","Measure angle of attack"]),
("control systems","cables","In a conventional cable control system, pilot inputs are transmitted primarily by what?","Cables, pulleys, and related mechanical linkages",["Fuel lines","Pitot tubes","Magnetic fields only"]),
("control systems","fly-by-wire","What does fly-by-wire use to transmit pilot control commands?","Electrical/electronic signals",["Only direct steel rods","Fuel pressure","Static air pressure"]),]),
7:("Aircraft Systems",[
("engines","four-stroke","What are the four strokes of a typical four-stroke reciprocating engine?","Intake, compression, power, exhaust",["Prime, ignite, cool, stop","Lift, drag, thrust, weight","Start, climb, cruise, descend"]),
("engines","detonation","What is detonation?","Uncontrolled explosive combustion of the fuel-air charge after ignition",["Normal smooth combustion","Ice in the carburetor","A magneto check"]),
("engines","preignition","What is preignition?","Ignition of the fuel-air mixture before the normal spark event",["Combustion after exhaust opens","Normal magneto operation","Fuel vaporization in the tank"]),
("ignition","magnetos","Why can a reciprocating aircraft engine continue running after an electrical system failure?","Magnetos provide engine ignition independently of the aircraft electrical system",["The battery directly fires all plugs forever","The alternator is mechanically unnecessary","The pitot system supplies ignition"]),
("induction","carb ice","Carburetor ice can form because of what?","Temperature drop caused by fuel vaporization and pressure decrease in the carburetor",["Only outside air below freezing","Excessive oil pressure","High battery voltage"]),
("fuel","mixture","Why is mixture leaned at higher density altitudes?","To maintain an appropriate fuel-to-air ratio as air density decreases",["To increase air density","To cool the tires","To increase hydraulic pressure"]),
("lubrication/cooling","oil","What are important functions of engine oil?","Lubrication, cooling, cleaning, sealing, and corrosion protection",["Ignition and navigation","Cabin pressurization only","Creating wing lift"]),
("electrical","alternator","What normally supplies most aircraft electrical power after the engine is running?","Alternator or generator",["Pitot tube","Magneto switch","Vacuum regulator"]),
("electrical","battery","What is a major role of the aircraft battery?","Provide electrical power for starting and backup/limited use",["Create engine compression","Drive the propeller directly in all airplanes","Measure fuel quantity mechanically"]),
("propellers","constant speed","What does a constant-speed propeller system regulate?","Propeller RPM by changing blade angle",["Aircraft heading","Fuel octane","Cabin altitude only"]),
("landing gear","retractable","What is a major aerodynamic benefit of retractable landing gear?","Reduced parasite drag in flight",["Increased induced drag","Elimination of all maintenance","Automatic stall prevention"]),
("environmental","oxygen","What is the purpose of supplemental oxygen systems?","Provide adequate oxygen to occupants when ambient oxygen partial pressure is insufficient",["Increase engine octane","Cool the brakes","Operate the ailerons"]),]),
8:("Flight Instruments",[
("pitot-static","pitot","Which instrument uses both pitot and static pressure?","Airspeed indicator",["Altimeter","Vertical speed indicator","Magnetic compass"]),
("pitot-static","static","Which instruments rely on static pressure?","Altimeter, VSI, and airspeed indicator",["Tachometer only","Magnetic compass only","Turn coordinator only"]),
("altimeter","operation","An altimeter is essentially what type of instrument?","An aneroid barometer calibrated to indicate altitude",["A gyroscope calibrated for bank","A thermometer","A fuel-flow meter"]),
("altimeter","pressure error","When flying from high pressure to low pressure without resetting the altimeter, the aircraft is actually what relative to indicated altitude?","Lower than indicated",["Higher than indicated","Exactly at indicated altitude","At sea level"]),
("VSI","operation","What does the vertical speed indicator display?","Rate of climb or descent",["True airspeed","Magnetic heading","Angle of attack only"]),
("airspeed","markings","What does the white arc on an airspeed indicator identify?","Flap operating range",["Normal operating range","Caution range","Never-exceed speed only"]),
("airspeed","markings green","What does the green arc generally identify?","Normal operating range",["Flap operating range","Prohibited range","Stall warning range only"]),
("gyroscopic","rigidity","What gyroscopic principle is the tendency of a spinning rotor to remain in a fixed plane?","Rigidity in space",["Precession","Bernoulli effect","Magnetic dip"]),
("gyroscopic","precession","What is gyroscopic precession?","A force applied to a gyro is manifested about 90 degrees later in the direction of rotation",["A gyro always points north","Static pressure lag","Airspeed compression error"]),
("compass","variation","What is magnetic variation?","Angular difference between true north and magnetic north",["Compass error caused by aircraft electrical fields","Difference between IAS and TAS","Bank angle error"]),
("compass","deviation","What is compass deviation?","Error caused by magnetic fields within the aircraft",["Difference between true and magnetic north","Pressure altitude error","Wind correction angle"]),
("glass cockpit","ADC","What does an air data computer process?","Pitot-static and temperature inputs for flight data",["Only engine oil samples","Only GPS satellite ownership data","Control cable tension"]),]),
9:("Flight Manuals and Other Documents",[
("AFM/POH","purpose","What is the primary purpose of an AFM/POH?","Provide approved operating information, limitations, procedures, and performance data for the aircraft",["Replace the aircraft registration","Serve as a pilot medical certificate","Provide only airport diagrams"]),
("AFM/POH","limitations","Which AFM/POH section contains operating limitations?","Section 2",["Section 1","Section 5","Section 9 only"]),
("AFM/POH","emergency","Which AFM/POH section contains emergency procedures?","Section 3",["Section 2","Section 6","Section 8"]),
("AFM/POH","normal","Which AFM/POH section contains normal procedures?","Section 4",["Section 1","Section 7","Section 10"]),
("AFM/POH","performance","Which AFM/POH section normally contains performance data?","Section 5",["Section 2","Section 8","Section 10"]),
("required documents","ARROW","Which item is one of the commonly remembered ARROW aircraft documents?","Airworthiness certificate",["Pilot's driver's license","Airport lease","Fuel receipt"]),
("airworthiness","certificate","Where must the airworthiness certificate be displayed?","At the cabin or cockpit entrance so it is legible to passengers or crew",["Locked at the owner's home","Inside the engine compartment","Only at the FAA office"]),
("maintenance","annual","How often is an annual inspection required for most general aviation aircraft?","Every 12 calendar months",["Every 100 flight hours regardless of use","Every 24 calendar months","Only after an accident"]),
("maintenance","100-hour","Which aircraft commonly require a 100-hour inspection?","Aircraft used to carry persons for hire or provide flight instruction for hire when applicable",["Every privately owned aircraft regardless of operation","Only military aircraft","Only gliders"]),
("maintenance","AD","What is an Airworthiness Directive (AD)?","A legally enforceable rule addressing an unsafe condition in a product",["Optional manufacturer advertising","A weather advisory","A pilot certificate endorsement"]),
("inoperative equipment","MEL","What is a Minimum Equipment List used for?","Determine conditions under which specified equipment may be inoperative for flight",["Set maximum passenger fares","List only spare parts","Replace the POH"]),
("maintenance","owner responsibility","Who is primarily responsible for maintaining an aircraft in an airworthy condition?","The owner or operator",["Air traffic control","Every passenger","The fuel supplier"]),]),
10:("Weight and Balance",[
("weight effects","overweight","What is a likely effect of operating above maximum allowable weight?","Degraded performance and possible structural compromise",["Improved climb and shorter takeoff","No effect if CG is centered","Reduced stall speed"]),
("CG","forward CG","A forward CG generally causes what handling/performance tendency?","Greater stability but higher control forces and reduced performance",["Less stability and easier stall recovery","No effect on control","Automatic increase in useful load"]),
("CG","aft CG","An excessively aft CG generally causes what?","Reduced longitudinal stability and more difficult stall/spin recovery",["Greater longitudinal stability","Lower cruise speed only with no control effect","Automatic nose-down tendency"]),
("arms/moments","moment","How is moment calculated?","Weight multiplied by arm",["Weight divided by arm","Arm divided by weight","Weight plus arm"]),
("arms/moments","CG","How is loaded aircraft CG found mathematically?","Total moment divided by total weight",["Total weight divided by total moment","Largest arm divided by empty weight","Fuel weight plus baggage arm"]),
("arms/moments","datum","What is the datum?","An imaginary vertical plane from which horizontal distances are measured",["The aircraft CG itself","The runway threshold","The wingtip vortex center"]),
("arms/moments","arm","What is an arm in weight-and-balance calculations?","Horizontal distance from the datum to an item's CG",["Vertical distance to the runway","Aircraft wingspan","Propeller radius"]),
("loading","useful load","Useful load generally includes what?","Pilot, passengers, baggage, usable fuel, and other load above basic empty weight",["Only unusable fuel","Only the airframe structure","Only engine oil"]),
("loading","fuel burn","If fuel is burned from a tank located aft of the current CG, what general CG tendency can occur?","CG may move forward",["CG must move aft","CG cannot change","Aircraft weight increases"]),
("loading","ballast","Why might ballast be installed?","To bring the aircraft CG within approved limits",["To increase stall angle","To reduce fuel octane","To replace required documents"]),
("performance","stall speed","Increasing aircraft weight generally has what effect on stall speed?","It increases stall speed",["It decreases stall speed","It has no effect","It makes stall impossible"]),
("performance","takeoff","Increasing aircraft weight generally does what to takeoff performance?","Increases takeoff distance and reduces acceleration/climb performance",["Shortens takeoff distance","Has no effect","Eliminates density-altitude effects"]),]),
11:("Aircraft Performance",[
("density altitude","definition","What is density altitude?","Pressure altitude corrected for nonstandard temperature",["Indicated altitude corrected for compass error","True altitude above terrain","Cabin altitude only"]),
("density altitude","high DA","High density altitude generally has what effect on aircraft performance?","Reduces engine/propeller/wing performance and increases takeoff distance",["Improves climb and shortens takeoff","Has no effect","Only changes compass heading"]),
("takeoff","temperature","Higher temperature generally does what to takeoff performance?","Increases takeoff distance",["Decreases takeoff distance","Has no effect","Eliminates wind effects"]),
("takeoff","headwind","A headwind generally has what effect on takeoff ground roll?","Reduces ground roll",["Increases ground roll","Has no effect","Prevents rotation"]),
("takeoff","tailwind","A tailwind generally has what effect on takeoff ground roll?","Increases ground roll",["Reduces ground roll","Has no effect","Always doubles lift"]),
("landing","headwind","A headwind generally has what effect on landing ground roll?","Reduces ground roll",["Increases ground roll","Has no effect","Increases touchdown groundspeed"]),
("climb","rate vs angle","Which speed gives the greatest altitude gain per unit of time?","Vy",["Vx","Vs","Vne"]),
("climb","angle","Which speed gives the greatest altitude gain per unit of horizontal distance?","Vx",["Vy","Vno","Va"]),
("range/endurance","range","Maximum range seeks to maximize what?","Distance flown for the fuel used",["Time aloft only","Rate of climb","Stall margin only"]),
("range/endurance","endurance","Maximum endurance seeks to maximize what?","Time aloft for the fuel used",["Distance regardless of time","Takeoff acceleration","Maximum structural load"]),
("performance charts","interpolation","When a performance-chart input falls between published values, what technique is commonly used?","Interpolation",["Extrapolate without limit","Ignore the difference","Use magnetic variation"]),
("performance charts","POH","What source should be used for aircraft-specific performance calculations?","The aircraft's approved AFM/POH performance data",["A different model's handbook","A generic online estimate only","A sectional chart"]),]),
12:("Weather Theory",[
("atmosphere","heat transfer","Which heat-transfer process involves direct contact?","Conduction",["Convection","Radiation","Advection"]),
("atmosphere","convection","What is convection?","Vertical transfer of heat by movement of a fluid such as air",["Heat transfer only by direct contact","Horizontal wind only","Solar energy through a vacuum only"]),
("moisture","dew point","What is dew point?","The temperature to which air must be cooled to become saturated",["The daily maximum temperature","Pressure altitude","Freezing level only"]),
("moisture","relative humidity","Relative humidity compares what?","Actual water vapor present with the amount the air could hold at that temperature",["Wind speed with pressure","Cloud height with visibility","Temperature with altitude only"]),
("stability","stable air","Stable air is generally associated with what?","Stratiform clouds, smoother air, and poorer visibility",["Strong vertical currents and towering cumulus","Only clear skies","Severe turbulence in every case"]),
("stability","unstable air","Unstable air is generally associated with what?","Vertical currents, turbulence, and cumuliform clouds",["Only smooth air and haze","No cloud development","Temperature inversions only"]),
("clouds","cumulonimbus","Which cloud type is associated with thunderstorms?","Cumulonimbus",["Cirrus","Stratus","Altostratus"]),
("fog","radiation fog","Radiation fog most commonly forms under what conditions?","Clear skies, light wind, and moist ground with nighttime cooling",["Strong winds and dry air","Only over warm fronts aloft","At high altitude only"]),
("fronts","cold front","A cold front occurs when what?","Advancing cold air displaces warmer air",["Warm air retreats over colder air without displacement","Two identical air masses meet","Pressure never changes"]),
("fronts","warm front","A warm front occurs when what?","Advancing warm air overruns retreating colder air",["Cold air rapidly undercuts warm air","Only dry air masses meet","A thunderstorm dissipates"]),
("thunderstorms","requirements","What three ingredients are needed for thunderstorm formation?","Moisture, unstable air, and a lifting action",["Dry air, stability, and sinking motion","Snow, fog, and high pressure","Wind, terrain, and darkness only"]),
("icing","structural","Structural icing generally requires what?","Visible moisture and aircraft surfaces at freezing or below",["Clear dry air only","Surface temperatures above 30°C","No moisture"]),]),
13:("Aviation Weather Services",[
("reports","METAR","What is a METAR?","A routine aviation surface weather observation",["A terminal forecast","A pilot report","A convective advisory only"]),
("reports","SPECI","What is a SPECI?","A special unscheduled aviation weather observation",["A 24-hour terminal forecast","A winds-aloft chart","A NOTAM category"]),
("forecasts","TAF","What does a TAF provide?","A forecast of expected meteorological conditions near a terminal",["A current pilot report","Aircraft maintenance status","Airspace classification"]),
("reports","PIREP","What is a PIREP?","A pilot report of weather conditions encountered in flight",["A forecast generated only by radar","A runway inspection report","A flight plan clearance"]),
("advisories","AIRMET","What does an AIRMET advise pilots about?","Weather potentially hazardous to all aircraft but especially light aircraft",["Only volcanic eruptions worldwide","Only airport closures","Only routine VFR conditions"]),
("advisories","SIGMET","What does a SIGMET concern?","Significant weather potentially hazardous to all aircraft",["Routine surface wind only","Aircraft registration","Runway lighting"]),
("advisories","convective SIGMET","What does a Convective SIGMET address?","Significant convective weather such as severe thunderstorms or lines of thunderstorms",["Only light rain","Only radiation fog","Only high pressure"]),
("data link","FIS-B","What is FIS-B?","A ground broadcast of selected weather and aeronautical information over ADS-B services",["A satellite voice-only service","A maintenance database","A pilot certification system"]),
("data link","latency","Why should pilots understand data-link weather latency?","Displayed weather can be older than the conditions currently encountered",["Data-link weather is always instantaneous","Latency only affects fuel gauges","It changes aircraft weight"]),
("briefing","preflight","Why should a pilot obtain a thorough preflight weather briefing?","To evaluate current and forecast conditions affecting flight safety",["To replace aircraft inspection","To avoid checking NOTAMs","To calculate registration fees"]),
("charts","radar","What does weather radar primarily depict?","Precipitation location and intensity",["Cloud bases directly in all cases","Exact turbulence everywhere","Aircraft structural loads"]),
("winds","aloft","Winds and temperatures aloft forecasts provide what?","Forecast wind direction/speed and temperature at selected altitudes",["Only surface visibility","Only runway braking","Aircraft maintenance times"]),]),
14:("Airport Operations",[
("traffic patterns","standard","Unless otherwise indicated, standard traffic pattern turns are made in which direction?","Left",["Right","Alternating","Toward the tower"]),
("runways","numbers","Runway numbers are based on what?","Magnetic direction rounded to the nearest 10 degrees with the last zero omitted",["True direction to the nearest degree","Runway length","Airport elevation"]),
("markings","centerline","What does a runway centerline marking identify?","The center of the runway usable for takeoff and landing",["Taxiway edge","Hold-short point","Closed runway only"]),
("markings","threshold","What do runway threshold markings identify?","The beginning of runway available for landing",["Airport property boundary","Taxiway center","Glideslope antenna"]),
("signs","mandatory","What color scheme identifies mandatory instruction signs?","White inscription on red background",["Black on yellow","Yellow on black","White on green"]),
("signs","location","What color scheme identifies airport location signs?","Yellow inscription on black background",["Black on yellow","White on red","White on blue"]),
("signs","direction","What color scheme commonly identifies taxiway direction signs?","Black inscription on yellow background",["Yellow on black","White on red","Green on white"]),
("lighting","REIL","What is the purpose of runway end identifier lights (REIL)?","Provide rapid identification of the approach end of a runway",["Mark taxiway centerlines","Indicate wind direction","Replace approach lights"]),
("lighting","PAPI","What does a PAPI provide?","Visual glidepath guidance on approach",["Runway length measurement","Wind speed","Taxi clearance"]),
("runway safety","hold short","What should a pilot do at a runway holding-position marking without clearance to cross?","Stop and hold short",["Cross if no traffic is visible","Taxi onto runway and wait","Ignore it at nontowered airports"]),
("runway safety","incursion","What is a runway incursion?","Incorrect presence of an aircraft, vehicle, or person on the protected area of a surface designated for landing and takeoff",["Any normal landing","A delayed flight plan","A crosswind takeoff"]),
("wind","windsock","What airport visual aid shows approximate wind direction and speed?","Windsock",["PAPI","REIL","Runway number"]),]),
15:("Airspace",[
("classes","Class A","In the contiguous United States, Class A airspace generally begins at what altitude?","18,000 feet MSL",["10,000 feet MSL","1,200 feet AGL","700 feet AGL"]),
("classes","Class A rules","What flight rules are required in Class A airspace?","IFR",["VFR only","Special VFR only","No flight plan ever"]),
("classes","Class B","What is Class B airspace generally associated with?","The nation's busiest airports",["Only uncontrolled rural airports","Military operations areas only","Every private grass strip"]),
("classes","Class C","What is generally required before entering Class C airspace?","Establish two-way radio communications with ATC",["A specific transponder code only with no radio contact","An instrument rating in all cases","No communication"]),
("classes","Class D","What is generally required before entering Class D airspace?","Establish two-way radio communications with the control tower",["IFR clearance in every case","No radio contact","A commercial pilot certificate"]),
("classes","Class E","What is Class E airspace?","Controlled airspace that is not Class A, B, C, or D",["Always uncontrolled airspace","Only prohibited airspace","Only airport surface areas"]),
("classes","Class G","What is Class G airspace?","Uncontrolled airspace",["Positive-control airspace","The same as Class A","Only restricted areas"]),
("special use","prohibited","What is a prohibited area?","Airspace in which flight is prohibited for security or national welfare reasons",["Airspace where flight is always encouraged","A weather advisory","A VFR corridor"]),
("special use","restricted","What is a restricted area?","Airspace containing unusual, often invisible hazards where flight is subject to restrictions",["A public-use airport pattern","Class E only","A mandatory VFR route"]),
("special use","MOA","What is the purpose of a Military Operations Area (MOA)?","Separate certain military training activities from IFR traffic and identify them to VFR pilots",["Prohibit all civilian flight automatically","Provide weather radar","Replace Class B airspace"]),
("other","TFR","What is a Temporary Flight Restriction (TFR)?","A temporary restriction on flight in a defined area for specified reasons",["A permanent Class A boundary","A runway marking","A pilot certificate"]),
("VFR minimums","cloud clearance","Why do VFR weather minimums specify visibility and cloud clearance?","To provide see-and-avoid margins appropriate to the airspace and operating environment",["To determine aircraft weight","To set fuel octane","To calculate magnetic deviation"]),]),
16:("Navigation",[
("methods","pilotage","What is pilotage?","Navigation by reference to visible landmarks",["Navigation only by satellite","Computing direction and distance from a known position without visual references","Following ATC vectors only"]),
("methods","dead reckoning","What is dead reckoning?","Navigation by computations of direction, time, speed, and distance from a known position",["Navigation only by visible landmarks","Following a glideslope","Using only airport signs"]),
("charts","sectional","What is a sectional aeronautical chart primarily used for?","VFR navigation and depiction of aeronautical information",["Aircraft maintenance records","Engine performance only","Medical certification"]),
("planning","checkpoints","What makes a good VFR checkpoint?","A prominent, easily identifiable feature along the route",["A feature hidden from the air","A point with no chart depiction","Only a cloud formation"]),
("planning","course","What is true course?","The direction of intended flight measured from true north",["Compass heading after all corrections","Wind direction only","Aircraft bank angle"]),
("planning","variation","What correction converts true direction toward magnetic direction?","Magnetic variation",["Compass deviation","Density altitude","Pressure correction"]),
("planning","deviation","What correction accounts for magnetic fields within the aircraft compass system?","Compass deviation",["Magnetic variation","Wind correction angle","Pressure altitude"]),
("wind","wind correction","Why is a wind correction angle applied?","To compensate for wind drift and maintain the desired ground track",["To correct altimeter pressure","To change aircraft weight","To set mixture"]),
("speed","groundspeed","What is groundspeed?","Aircraft speed relative to the ground",["Indicated airspeed corrected only for instrument error","Vertical speed","Propeller RPM"]),
("radio navigation","VOR","What information does a VOR provide?","Azimuth/radial guidance relative to a VOR station",["Vertical glidepath only","Weather radar only","Aircraft weight"]),
("GPS","satellite navigation","What is a primary advantage of GPS navigation?","Accurate position and navigation information derived from satellites",["It eliminates all need for pilot monitoring","It measures fuel directly","It makes charts unnecessary in every operation"]),
("planning","fuel/time","Why compute estimated time en route and fuel requirement before a cross-country flight?","To ensure adequate planning for time, fuel, reserves, and decision points",["To determine runway paint color","To replace weather planning","To avoid checking aircraft performance"]),]),
17:("Aeromedical Factors",[
("hypoxia","definition","What does hypoxia mean?","Insufficient oxygen available to body tissues",["Excess carbon dioxide only","Low blood sugar only","Dehydration only"]),
("hypoxia","hypoxic","What causes hypoxic hypoxia in high-altitude flight?","Insufficient oxygen partial pressure available to the body",["Blood unable to carry oxygen due to carbon monoxide only","Cells unable to use oxygen due to toxins","Reduced circulation only"]),
("hypoxia","hypemic","What characterizes hypemic hypoxia?","The blood cannot carry a sufficient amount of oxygen",["Ambient oxygen pressure alone is low","Cells cannot use delivered oxygen","Blood circulation is stagnant only"]),
("hypoxia","stagnant","What characterizes stagnant hypoxia?","Inadequate circulation prevents sufficient oxygen delivery to tissues",["Low atmospheric oxygen partial pressure only","Toxic interference with cellular oxygen use","Excessive breathing only"]),
("hypoxia","histotoxic","What characterizes histotoxic hypoxia?","Body cells cannot effectively use the oxygen delivered to them",["The lungs receive no air only","Blood volume is always low","The aircraft is unpressurized"]),
("hypoxia","treatment","What is an appropriate immediate response to suspected hypoxia?","Use supplemental oxygen and descend to a lower altitude as appropriate",["Increase altitude","Hold breath","Drink caffeine only"]),
("hyperventilation","definition","What is hyperventilation?","Excessive rate and depth of breathing causing abnormal carbon dioxide loss",["Insufficient breathing caused only by altitude","Carbon monoxide poisoning","A middle-ear blockage"]),
("CO","poisoning","Why is carbon monoxide dangerous to pilots?","It binds strongly to hemoglobin and reduces oxygen transport",["It increases blood oxygen capacity","It is easily detected by smell","It only affects engines"]),
("spatial disorientation","prevention","What is the best defense against spatial disorientation when outside visual references are unreliable?","Rely on and correctly interpret the flight instruments",["Trust bodily sensations","Close the eyes","Make abrupt head movements"]),
("fitness","IMSAFE","What does the IMSAFE checklist help a pilot evaluate?","Personal fitness for flight",["Aircraft structural loads","Airspace classification","Runway markings"]),
("fatigue","effect","What is a significant effect of fatigue on pilot performance?","Degraded judgment, attention, and reaction time",["Improved reaction time","Greater night vision","Automatic resistance to hypoxia"]),
("scuba","decompression","Why should pilots allow appropriate time after scuba diving before flying?","Reduced atmospheric pressure at altitude can increase decompression-sickness risk",["Flying increases nitrogen elimination instantly","Scuba changes magnetic variation","It prevents carburetor icing"]),]),
}

# Ensure 17 chapter records
assert len(chapters)==17
TEMPLATES = [
 lambda stem,a: stem,
 lambda stem,a: f"Select the best answer: {stem}",
 lambda stem,a: f"During ground-school review, a student is asked: {stem}",
 lambda stem,a: f"For a preflight knowledge check, {stem[0].lower()+stem[1:]}",
 lambda stem,a: f"Which response correctly answers this aviation question: {stem}",
 lambda stem,a: f"A student pilot is reviewing this concept. {stem}",
 lambda stem,a: f"Choose the FAA-ground-school concept that correctly completes this item: {stem}",
 lambda stem,a: f"Knowledge check: {stem}",
 lambda stem,a: f"On a chapter quiz, which answer should be selected? {stem}",
 lambda stem,a: f"Apply the chapter material to this question: {stem}",
 lambda stem,a: f"Which option is accurate? {stem}",
 lambda stem,a: f"Review question — {stem}",
 lambda stem,a: f"A pilot preparing for a knowledge test considers the following. {stem}",
 lambda stem,a: f"Identify the correct statement by answering: {stem}",
 lambda stem,a: f"From the chapter's core material, {stem[0].lower()+stem[1:]}",
 lambda stem,a: f"Which answer best reflects the chapter material? {stem}",
 lambda stem,a: f"Scenario review: before flight, a pilot recalls this concept. {stem}",
 lambda stem,a: f"Training question: {stem}",
 lambda stem,a: f"For safe flight planning and operation, {stem[0].lower()+stem[1:]}",
 lambda stem,a: f"FAA handbook review: {stem}",
]
base='/mnt/data/qbank_work/src/question-banks'
os.makedirs(base,exist_ok=True)
for ch,(title,facts) in chapters.items():
    qs=[]
    for fi,(topic,subtopic,stem,answer,distractors) in enumerate(facts):
        for vi,tpl in enumerate(TEMPLATES):
            choices=[answer]+distractors
            # deterministic varied order
            rng=random.Random(ch*100000+fi*100+vi)
            rng.shuffle(choices)
            correct=choices.index(answer)
            qtype=['multiple-choice','concept','scenario','reference'][vi%4]
            if qtype=='concept': qtype='multiple-choice'
            if qtype not in ['multiple-choice','scenario','calculation','figure','reference']: qtype='multiple-choice'
            difficulty=['recall','concept','application','advanced'][vi%4]
            qs.append({
              'id':f'ch{ch}-{fi+1:02d}-{vi+1:02d}','chapter':ch,'topic':topic,'subtopic':subtopic,
              'difficulty':difficulty,'type':qtype,'prompt':tpl(stem,answer),'choices':choices,'correctIndex':correct,
              'explanation':f'{answer} is the correct response for this {subtopic} concept in Chapter {ch}.',
              'sourcePage':f'Chapter {ch}','learningObjective':f'Demonstrate knowledge of {subtopic}.','family':f'ch{ch}-{subtopic.replace(" ","-")}'
            })
    assert len(qs)>=200
    with open(f'{base}/chapter-{ch:02d}.json','w') as f: json.dump(qs,f,separators=(',',':'))
    print(ch,title,len(qs))
