-- Run this in the Supabase SQL editor once.
create table if not exists public.student_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  completed_modules integer[] not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.student_progress enable row level security;

create policy "Students can read their own progress"
on public.student_progress for select
using (auth.uid() = user_id);

create policy "Students can create their own progress"
on public.student_progress for insert
with check (auth.uid() = user_id);

create policy "Students can update their own progress"
on public.student_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- V2 course progress: automatic module percentages rather than manual completion.
alter table public.student_progress
  add column if not exists module_progress jsonb not null default '{}'::jsonb;

-- Quiz attempts: records required module assessments for signed-in students.
create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id integer not null check (module_id between 1 and 17),
  score integer not null check (score between 0 and 100),
  passed boolean not null default false,
  question_count integer not null default 20,
  attempted_at timestamptz not null default now()
);
alter table public.quiz_attempts enable row level security;
create policy "Students can read their own quiz attempts" on public.quiz_attempts for select using (auth.uid() = user_id);
create policy "Students can create their own quiz attempts" on public.quiz_attempts for insert with check (auth.uid() = user_id);

-- Optional server-side quiz draft storage for future cross-device resume support.
-- Current website auto-saves unfinished quizzes locally on the student's device.
create table if not exists public.quiz_drafts (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_id integer not null check (module_id between 1 and 17),
  question_ids jsonb not null default '[]'::jsonb,
  answers jsonb not null default '{}'::jsonb,
  current_index integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, module_id)
);
alter table public.quiz_drafts enable row level security;
create policy "Students can read their own quiz drafts" on public.quiz_drafts for select using (auth.uid() = user_id);
create policy "Students can create their own quiz drafts" on public.quiz_drafts for insert with check (auth.uid() = user_id);
create policy "Students can update their own quiz drafts" on public.quiz_drafts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Students can delete their own quiz drafts" on public.quiz_drafts for delete using (auth.uid() = user_id);
